"""
build_cell_library.py - Derive cell_library.json from the benchmark netlists.

For every standard-cell type seen in the 37 Interconnected-Modules netlists, record
the union of pin names used by its instances and classify each pin as input or
output.  Direction rule: pins in OUTPUT_PIN_NAMES are outputs, all others inputs
(the same fallback netlist_graph_engine applies to cells missing from the library).

Usage (from ML_VLSI/):
    python tools/build_cell_library.py
"""

import glob
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, ROOT)

from netlist_graph_engine import parse_verilog_netlist, OUTPUT_PIN_NAMES  # noqa: E402
from circuit_store import DATASET_DIR  # noqa: E402

OUT_PATH = os.path.join(ROOT, 'cell_library.json')


def build_library(netlist_paths):
    pins_by_cell = {}
    variants = {}
    for path in netlist_paths:
        parsed = parse_verilog_netlist(path)
        for gate in parsed['gates']:
            cell = gate['cell_type']
            pin_set = frozenset(gate['pins'])
            pins_by_cell.setdefault(cell, set()).update(pin_set)
            variants.setdefault(cell, set()).add(pin_set)

    library = {}
    for cell in sorted(pins_by_cell):
        pins = pins_by_cell[cell]
        library[cell] = {
            'inputs': sorted(p for p in pins if p.upper() not in OUTPUT_PIN_NAMES),
            'outputs': sorted(p for p in pins if p.upper() in OUTPUT_PIN_NAMES),
        }
    inconsistent = sorted(c for c, v in variants.items() if len(v) > 1)
    return library, inconsistent


if __name__ == '__main__':
    paths = sorted(glob.glob(os.path.join(DATASET_DIR, '*.v')))
    library, inconsistent = build_library(paths)
    with open(OUT_PATH, 'w', encoding='utf-8') as f:
        json.dump({
            '_comment': 'Generated by tools/build_cell_library.py from the Interconnected-Modules '
                        'benchmarks. Cells not listed here fall back to: pins in '
                        + '/'.join(sorted(OUTPUT_PIN_NAMES)) + ' are outputs, all others inputs.',
            'cells': library,
        }, f, indent=1, sort_keys=False)
    print(f'Wrote {len(library)} cell types from {len(paths)} netlists to {OUT_PATH}')
    if inconsistent:
        print('WARNING: cells with inconsistent pin sets across instances:', inconsistent)
